/*
 * MyLogin.java
 * Created on __DATE__, __TIME__
 */

package com.amar.wiget.swing;

import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 * @author __USER__
 */
public class MyLogin extends javax.swing.JFrame
{

	private static final long serialVersionUID = - 2462634626677379354L;

	/** Creates new form MyLogin */
	public MyLogin()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree( root );
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();

		setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

		jScrollPane1.setViewportView( jTree1 );

		jTable1.setModel( new javax.swing.table.DefaultTableModel( new Object [] [] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null }, { null, null, null, null } } ,
				new String [] { "Title 1", "Title 2", "Title 3", "Title 4" } ) );
		jScrollPane2.setViewportView( jTable1 );

		jLabel1.setText( "jLabel1" );

		jMenu1.setText( "File" );
		jMenuBar1.add( jMenu1 );

		jMenu2.setText( "Edit" );

		jMenuItem1.setText( "Item" );
		jMenu2.add( jMenuItem1 );

		jMenuBar1.add( jMenu2 );

		setJMenuBar( jMenuBar1 );

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
		getContentPane().setLayout( layout );
		layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup()
						.addGroup(
								layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
										.addGroup(
												layout.createSequentialGroup().addContainerGap()
														.addComponent( jScrollPane1 , javax.swing.GroupLayout.PREFERRED_SIZE , 128 , javax.swing.GroupLayout.PREFERRED_SIZE ).addGap( 32 , 32 , 32 )
														.addComponent( jScrollPane2 , javax.swing.GroupLayout.PREFERRED_SIZE , 452 , javax.swing.GroupLayout.PREFERRED_SIZE ) )
										.addGroup( layout.createSequentialGroup().addGap( 73 , 73 , 73 ).addComponent( jLabel1 ) ) ).addContainerGap( 33 , Short.MAX_VALUE ) ) );
		layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING , false )
										.addComponent( jScrollPane2 , javax.swing.GroupLayout.Alignment.LEADING , 0 , 0 , Short.MAX_VALUE )
										.addComponent( jScrollPane1 , javax.swing.GroupLayout.Alignment.LEADING ) ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
						.addComponent( jLabel1 ).addGap( 13 , 13 , 13 ) ) );

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] )
	{
		java.awt.EventQueue.invokeLater( new Runnable()
		{
			public void run()
			{
				MyLogin login = new MyLogin();
				login.setVisible( true );

				login.initTable();
				login.initTree();
			}
		} );
	}

	private DefaultMutableTreeNode root = new DefaultMutableTreeNode( "中国" );

	public void initTree()
	{
		// jTree1
		DefaultMutableTreeNode guangdong = new DefaultMutableTreeNode( "广东" );
		DefaultMutableTreeNode guangxi = new DefaultMutableTreeNode( "广西" );
		DefaultMutableTreeNode foshan = new DefaultMutableTreeNode( "佛山" );
		DefaultMutableTreeNode shantou = new DefaultMutableTreeNode( "汕头" );
		DefaultMutableTreeNode guilin = new DefaultMutableTreeNode( "桂林" );
		DefaultMutableTreeNode nanning = new DefaultMutableTreeNode( "南宁" );

		guangdong.add( foshan );
		guangdong.add( shantou );
		guangxi.add( guilin );
		guangxi.add( nanning );
		root.add( guangdong );
		root.add( guangxi );
		jTree1 = new JTree( root );

	}

	public void initTable()
	{
		Object [][] value = new Object [ 30 ] [ 5 ];
		for( int j = 0 ; j < 30 ; j ++ )
		{
			for( int i = 0 ; i < 5 ; i ++ )
			{
				value[ j ][ i ] = j + "-" + i;
			}
		}
		String title[] = new String [] { "标题1", "标题2", "标题3", "标题4", "标题5" };
		jTable1.setModel( new javax.swing.table.DefaultTableModel( value , title ) );
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;

	private javax.swing.JMenu jMenu1;

	private javax.swing.JMenu jMenu2;

	private javax.swing.JMenuBar jMenuBar1;

	private javax.swing.JMenuItem jMenuItem1;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JScrollPane jScrollPane2;

	private javax.swing.JTable jTable1;

	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables

}
